# Generated by Django 5.0.7 on 2024-07-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("overview", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("poster", models.ImageField(upload_to="posters/")),
                ("backdrop", models.ImageField(upload_to="backdrops/")),
                ("original_title", models.CharField(max_length=100)),
                ("original_language", models.CharField(max_length=50)),
                ("popularity", models.FloatField()),
                ("vote_average", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
